Repository WIT-BinBot-2020/pxt-binbot-wit-2020, pull requests merged in 2020-03, with the labels that each got.

#24 Added servo mouth test code
  pi_hub_python/mouth/servo.py
Labels: enhancement

#28 Add servo mouth
  pi_hub_python/mouth/servo.py
  pi_hub_python/pi_hub.py
  pi_hub_python/requirements.txt
Labels: enhancement

#31 Keyword detection
  main.ts
  pi_hub_python/ears/ears.py
  pi_hub_python/pi_hub.py
Labels: enhancement

#32 Keyword detection
  main.ts
Labels: bug

#33 bug fixes 2
  main.ts
Labels: bug

#35 Keyword detection
  main.ts
Labels: bug

#36 Bug fixes 5
  main.ts
Labels: bug

#37 Several Bug Fixes
  main.ts
Labels: bug

#38 Final Fix pls
  main.ts
Labels: bug

#39 Last fix 2
  main.ts
Labels: bug

#40 Object detection
  pi_hub_python/eyes/eyes-test.py
  pi_hub_python/eyes/eyes.py
  pi_hub_python/eyes/object-detection.py
  pi_hub_python/pi_hub.py
Labels: enhancement

#41 Keyword detection
  main.ts
  pi_hub_python/packet_encoding.py
  pi_hub_python/pi_hub.py
Labels: bug, enhancement

#43 Keyword detection
  main.ts
Labels: bug

#44 Print statements, object coords vairable and function changes
  main.ts
Labels: bug

#45 Troubleshooting
  main.ts
Labels: bug
